"use client";

import { motion } from "framer-motion";
import { GalleryGrid } from "@/components/GalleryGrid";
import { type PageData } from "@/components/PageCard";

interface HomePageProps {
  pages: PageData[];
}

export function HomePage({ pages }: HomePageProps) {
  return (
    <div className="min-h-screen bg-black text-white selection:bg-accent/30 font-sans">
      <nav className="sticky top-0 z-50 w-full border-b border-white/5 bg-black/50 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 group cursor-pointer">
            <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center font-bold text-black italic transition-transform group-hover:rotate-12">
              A
            </div>
            <span className="font-bold tracking-tighter text-xl">AI SHOWCASE</span>
          </div>

          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-zinc-400">
            <a href="#" className="hover:text-white transition-colors">Gallery</a>
            <a href="#" className="hover:text-white transition-colors">Categories</a>
            <a href="#" className="hover:text-white transition-colors">About</a>
          </div>

          <button className="px-5 py-2 bg-white text-black text-xs font-bold rounded-full hover:bg-zinc-200 transition-all hover:scale-105 active:scale-95">
            Submit Page
          </button>
        </div>
      </nav>

      <header className="relative pt-24 pb-12 overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 bg-accent/20 blur-[120px] -z-10 rounded-full" />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <h1 className="text-4xl sm:text-6xl lg:text-7xl font-bold tracking-tight mb-6 bg-gradient-to-b from-white to-zinc-500 bg-clip-text text-transparent">
              Curated AI Page
              <br />
              Showcase & Prompts
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-zinc-400 leading-relaxed">
              Discover beautiful web pages generated by AI. Browse designs, preview live-style captures, and copy the prompts to build your own.
            </p>
          </motion.div>
        </div>
      </header>

      <main>
        <GalleryGrid initialPages={pages} />
      </main>

      <footer className="border-t border-white/5 py-12 mt-20 bg-zinc-950">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-zinc-800 rounded flex items-center justify-center font-bold text-[10px] italic">
              A
            </div>
            <span className="font-bold tracking-tighter text-sm">AI SHOWCASE © 2026</span>
          </div>

          <div className="flex gap-8 text-xs font-medium text-zinc-500 font-sans">
            <a href="#" className="hover:text-zinc-300 transition-colors">Twitter</a>
            <a href="#" className="hover:text-zinc-300 transition-colors">GitHub</a>
            <a href="#" className="hover:text-zinc-300 transition-colors">Discord</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
